name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            RELEASE_NAME: windows

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create custom JVM with jlink
        run: ./gradlew jlink
      - name: Preparation for archiving
        run: |
          sleep 15
          mkdir distribution
          mv build/image distribution/jre
          cp build/launch4j/sailly* distribution/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.RELEASE_NAME }}
          path: distribution